#:schema node_modules/wrangler/config-schema.json
name = "registry"
pages_build_output_dir = "public"
compatibility_date = "2024-05-12"
compatibility_flags = [ "nodejs_compat" ]
[vars]
SELF_AUTH = "true"
WHITE_LIST = "vswen55"
